FROM signoz/signoz-otel-collector:latest

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
COPY signoz/otel-collector-opamp-config.yaml /etc/manager-config.yaml

EXPOSE 4318 13133 1777 8888

CMD ["signoz-otel-collector", "--config=/etc/otel-collector-config.yaml", "--manager-config=/etc/manager-config.yaml", "--feature-gates=-pkg.translator.prometheus.NormalizeName"]