FROM signoz/signoz:latest

COPY signoz/prometheus.yml /root/config/prometheus.yml
COPY dashboards /root/config/dashboards

# Start SigNoz server with custom config
CMD ["signoz", "server", "--config=/root/config/prometheus.yml"]
