FROM signoz/signoz-otel-collector:latest

COPY ./otel-collector-config.yaml /etc/otel-collector-config.yaml
COPY signoz/otel-collector-opamp-config.yaml /etc/manager-config.yaml

# Expose ports for telemetry ingestion
EXPOSE 4317 4318 8082

# Start the collector with custom config
CMD ["signoz-otel-collector", "--config=/etc/otel-collector-config.yaml", "--manager-config=/etc/manager-config.yaml", "--feature-gates=-pkg.translator.prometheus.NormalizeName"]
